name: Docker Build and Run

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: docker_build_image
        run: docker build -t hello_world .

      - name: docker_run_container
        run: docker run hello_world

      - name: display_output
        run: echo "${{ steps.docker_run_container.outputs.output }}"
