# Workflow: Model Testing on PR
#
# Description: This GitHub Actions workflow triggers the testing of a machine learning
#              whenever a commit is added and a PR is opened against the default main.

name: Model Testing

on:
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Volume
        run: mkdir volume

      - name: Docker Build Image
        run: docker build -t eval .

      - name: Docker Evaluate Model
        run: docker run -e WANDB_USER_NAME=${{ secrets.WANDB_USER_NAME }} -e WANDB_API_KEY=${{ secrets.WANDB_API_KEY }} -v $PWD/volume:/volume eval

      # Read results from local folder
      - name: Read results from local folder
        run: python .github/workflows/json_to_md.py volume/test_results.json volume/test_results.md

      # Comment test results on PR
      - name: Comment test results on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: volume/test_results.md
