name: Trigger Model Testing On Comment

on:
  issue_comment:
    types: [created]

jobs:
  model-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Trigger Comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const triggerPhrase = '/test-model';
            const commentBody = context.payload.comment.body;

            if (commentBody.includes(triggerPhrase)) {
              console.log('Triggering workflow...');
              return 'success';
            } else {
              console.log('No trigger phrase found. Skipping workflow.');
              return 'skipped';
            }
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t train .

      - name: Run Docker Container
        run: docker run -e WANDB_USER_NAME=${{ secrets.WANDB_USER_NAME }} -e WANDB_API_KEY=${{ secrets.WANDB_API_KEY }} train
