# Workflow: Model Testing on PR
#
# Description: This GitHub Actions workflow triggers the testing of a machine learning
#              whenever a commit is added and a PR is opened against the default main.

name: Model Testing

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Build Image
        run: docker build -t train .

      - name: Docker Train & Test Model
        run: docker run -e WANDB_USER_NAME=${{ secrets.WANDB_USER_NAME }} -e WANDB_API_KEY=${{ secrets.WANDB_API_KEY }} train